export const SET_YEAR = 'SET_YEAR';
export const GET_PHOTOS_REQUEST = 'GET_PHOTOS_REQUEST';
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS';
export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_NAME_SUCCESS = 'CHANGE_NAME_SUCCESS';